table 'Masse salariale'
	lineageTag: 5056f410-0785-4e07-8e63-cad4a7f3c499

	measure 'Payroll Amount' = SUM('Masse salariale'[Payroll])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ab

	measure 'Payroll Amount Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Payroll Amount], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: 620ddca3-0cde-4da7-8eb8-6f2c21f6aaa8

	measure 'Payroll HUB' = SUM('Masse salariale'[PayrollHUB])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b5808d2f-bde5-405f-a29f-b49ece52f6a0

	measure 'HUB Share' = AVERAGE('Masse salariale'[HUBShare])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: 8141de85-a233-4ce0-bb73-9a0941e7196a

	measure 'HUB Share Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([HUB Share], 'Masse salariale'[DATE] = _lastDate)
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: 6b27faea-7ba8-4253-a837-220161d07900

	measure 'Overtime Hours' = SUM('Masse salariale'[OvertimeHours])
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: e0829d63-f6a5-440d-bfa4-66b4016dc407

	measure 'Overtime Hours Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Overtime Hours], 'Masse salariale'[DATE] = _lastDate)
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: c427f122-fbc0-4a34-aa7b-649a7aa7268e

	measure 'Payroll Budget' = SUM('Masse salariale'[PayrollBudget])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ac

	measure 'Payroll Budget Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Payroll Budget], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ad

	measure 'Overtime Cost' = SUM('Masse salariale'[OvertimeCost])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b2

	measure 'Leave Balance' = SUM('Masse salariale'[LeaveBalance])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ae

	measure 'Leave Balance Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Leave Balance], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8af

	measure 'Leave Provision' = SUM('Masse salariale'[LeaveProvision])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b0

	measure 'Leave Provision Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Leave Provision], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b1

	measure 'Leave Provision Budget Proxy Latest' = [Payroll Budget Latest]
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b7

	measure 'Leave Provision Budget Proxy' = [Payroll Budget]
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c0

	measure 'Leave Provision Scenario Value' =
			VAR _scenario = SELECTEDVALUE(Scenario[Scenario], "Réalisé")
			RETURN IF(_scenario = "Budget", [Leave Provision Budget Proxy Latest], [Leave Provision Latest])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b8

	measure 'Staff Cost Consumed %' = DIVIDE([Payroll Amount Latest], [Payroll Budget Latest])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b9

	measure 'Leave Provision Consumed %' = DIVIDE([Leave Provision Latest], [Leave Provision Budget Proxy Latest])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ba

	measure 'Staff Cost Consumed (Context) %' = DIVIDE([Payroll Amount], [Payroll Budget])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c1

	measure 'Leave Provision Consumed (Context) %' = DIVIDE([Leave Provision], [Leave Provision Budget Proxy])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c2

	column DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c88bf51-a80b-409b-afb4-e70f11c363b1
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Payroll
		dataType: int64
		formatString: 0
		lineageTag: c3e97ec2-8fd0-46d5-902a-b030bcce154e
		summarizeBy: sum
		sourceColumn: Payroll

		annotation SummarizationSetBy = Automatic

	column PayrollHUB
		dataType: int64
		formatString: 0
		lineageTag: 16188af8-f003-4868-9692-258952ad368f
		summarizeBy: sum
		sourceColumn: PayrollHUB

		annotation SummarizationSetBy = Automatic

	column HUBShare
		dataType: double
		lineageTag: 27b6d541-75fd-47d7-bc1d-475f67c68eac
		summarizeBy: sum
		sourceColumn: HUBShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OvertimeHours
		dataType: double
		lineageTag: fa2162e2-1240-414f-956e-5de43015896a
		summarizeBy: sum
		sourceColumn: OvertimeHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayrollBudget
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b3
		summarizeBy: sum
		sourceColumn: PayrollBudget

		annotation SummarizationSetBy = Automatic

	column OvertimeCost
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b4
		summarizeBy: sum
		sourceColumn: OvertimeCost

		annotation SummarizationSetBy = Automatic

	column LeaveBalance
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b5
		summarizeBy: sum
		sourceColumn: LeaveBalance

		annotation SummarizationSetBy = Automatic

	column LeaveProvision
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b6
		summarizeBy: sum
		sourceColumn: LeaveProvision

		annotation SummarizationSetBy = Automatic

	partition 'Masse salariale' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    #"Masse salariale_Sheet" = Source{[Item="Masse salariale",Kind="Sheet"]}[Data],
				    #"PromoteHeaders" = Table.PromoteHeaders(#"Masse salariale_Sheet", [PromoteAllScalars=true]),
				    _cols = Table.ColumnNames(#"PromoteHeaders"),
				    #"KeepColumns" = Table.SelectColumns(#"PromoteHeaders", {_cols{0}, _cols{1}, _cols{2}, _cols{3}, _cols{4}, _cols{5}, _cols{6}, _cols{7}, _cols{8}}),
				    #"RenameColumns" = Table.RenameColumns(#"KeepColumns", {{_cols{0}, "DATE"}, {_cols{1}, "PayrollBudget"}, {_cols{2}, "Payroll"}, {_cols{3}, "PayrollHUB"}, {_cols{4}, "HUBShare"}, {_cols{5}, "OvertimeHours"}, {_cols{6}, "OvertimeCost"}, {_cols{7}, "LeaveBalance"}, {_cols{8}, "LeaveProvision"}}),
				    #"MonthlyRows" = Table.FirstN(#"RenameColumns", each (try Number.From([DATE]) otherwise null) <> null),
				    #"NormalizeDate" = Table.TransformColumns(#"MonthlyRows", {{"DATE", each Number.From(_), type number}}),
				    #"ConvertDate" = Table.TransformColumns(#"NormalizeDate", {{"DATE", each Date.AddDays(#date(1899, 12, 30), _), type date}}),
				    #"ChangedType" = Table.TransformColumnTypes(#"ConvertDate", {{"PayrollBudget", Int64.Type}, {"Payroll", Int64.Type}, {"PayrollHUB", Int64.Type}, {"HUBShare", type number}, {"OvertimeHours", type number}, {"OvertimeCost", Int64.Type}, {"LeaveBalance", Int64.Type}, {"LeaveProvision", Int64.Type}})
				in
				    #"ChangedType"

	annotation PBI_ResultType = Table

