table 'TCDP Level Dim'
	lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8231

	column Level
		dataType: string
		lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8232
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column 'Level Order'
		dataType: int64
		formatString: 0
		lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8233
		summarizeBy: sum
		sourceColumn: "Level Order"

		annotation SummarizationSetBy = Automatic

	partition 'TCDP Level Dim' = m
		mode: import
		source =
				let
				    Source = Table.Combine(
				        {
				            Table.SelectColumns(#"TCDP Levels", {"Level"}),
				            Table.SelectColumns(#"TCDP Gender", {"Level"}),
				            Table.SelectColumns(#"TCDP Sorties", {"Level"})
				        }
				    ),
				    #"ChangedType" = Table.TransformColumnTypes(Source, {{"Level", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"Level", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [Level] <> null and [Level] <> ""),
				    #"DistinctRows" = Table.Distinct(#"FilteredRows"),
				    #"AddedCustom" = Table.AddColumn(#"DistinctRows", "Level Order", each if [Level] = "Level 1" then 1 else if [Level] = "Level 2A" then 2 else if [Level] = "Level 2B" then 3 else if [Level] = "Level 2C" then 4 else if [Level] = "Level 3" then 5 else if [Level] = "Level 3A" then 6 else if [Level] = "Level 3B" then 7 else if [Level] = "Level 3C" then 8 else if [Level] = "Level 4" then 9 else 99, Int64.Type),
				    #"SortedRows" = Table.Sort(#"AddedCustom", {{"Level Order", Order.Ascending}, {"Level", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table
