table Embauche
	lineageTag: f0e6abf9-fb25-4106-a3e1-21342bd0825d

	column 'Type d''entrée dans la société'
		dataType: string
		lineageTag: fef22c50-864e-452d-97ba-beb20b4db456
		summarizeBy: none
		sourceColumn: Type d'entrée dans la société

		annotation SummarizationSetBy = Automatic

	column 'Motif de recrutement'
		dataType: string
		lineageTag: e6c72c33-f7e9-4685-a74f-2910379ef93d
		summarizeBy: none
		sourceColumn: Motif de recrutement

		annotation SummarizationSetBy = Automatic

	column Société
		dataType: string
		lineageTag: 54fb48e4-d529-4791-8334-e5329eb74e73
		summarizeBy: none
		sourceColumn: Société

		annotation SummarizationSetBy = Automatic

	column Matricule
		dataType: string
		lineageTag: b4428a6a-3e6a-4c88-8ce2-37b339d64134
		summarizeBy: none
		sourceColumn: Matricule

		annotation SummarizationSetBy = Automatic

	column 'User ID'
		dataType: int64
		formatString: 0
		lineageTag: a8304da1-e8d4-4abc-b2cb-5d8c71c439c6
		summarizeBy: count
		sourceColumn: User ID

		annotation SummarizationSetBy = Automatic

	column Nom
		dataType: string
		lineageTag: 70a24846-ae62-4624-8a38-82a3a59d067b
		summarizeBy: none
		sourceColumn: Nom

		annotation SummarizationSetBy = Automatic

	column Prénom
		dataType: string
		lineageTag: dd477e10-e672-48e5-9d97-f59518398a89
		summarizeBy: none
		sourceColumn: Prénom

		annotation SummarizationSetBy = Automatic

	column Sexe
		dataType: string
		lineageTag: 2fb95b90-32d3-41cd-bc3a-86bf723b1156
		summarizeBy: none
		sourceColumn: Sexe

		annotation SummarizationSetBy = Automatic

	column 'Date de naissance'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62bfcee6-b58c-4526-a3f1-7a2694b46bb1
		summarizeBy: none
		sourceColumn: Date de naissance

		variation Variation
			isDefault
			relationship: 8cdeef1a-3612-4c4a-a432-1a1ae7246be9
			defaultHierarchy: LocalDateTable_58b78319-f172-4100-8539-c549d0ec522c.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: dc75e986-8d78-4261-b1a9-54dfdd7cdcbd
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Date d''embauche'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 41545057-3895-4b13-8fc3-34da2a44a737
		summarizeBy: none
		sourceColumn: Date d'embauche

		variation Variation
			isDefault
			relationship: 4efef294-090a-46c1-863b-4966ca1bdbef
			defaultHierarchy: LocalDateTable_8a180b59-e9e8-4511-b8f6-eb29fddd0f7d.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Direction
		dataType: string
		lineageTag: 61b9bf86-415b-4f70-8523-cca3922cb9c1
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column Département
		dataType: string
		lineageTag: c3756f96-f1f4-4be4-be9e-e4661b6c2bd6
		summarizeBy: none
		sourceColumn: Département

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: a7b866fc-c9eb-4d7b-b121-8240a4a8fdfe
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column 'Poste harmonisé'
		dataType: string
		lineageTag: fb131f69-c9f2-4a16-ac56-04c92e4ca330
		summarizeBy: none
		sourceColumn: Poste harmonisé

		annotation SummarizationSetBy = Automatic

	column Fonction
		dataType: string
		lineageTag: 68ce17d8-e5b3-48aa-8087-775e20d733ec
		summarizeBy: none
		sourceColumn: Fonction

		annotation SummarizationSetBy = Automatic

	column 'Date d''entrée'
		dataType: dateTime
		formatString: Long Date
		lineageTag: adcee7cb-fb4b-4c94-b632-f12ee099e5d7
		summarizeBy: none
		sourceColumn: Date d'entrée

		variation Variation
			isDefault
			relationship: 4aa19c41-febc-44c1-bf7f-df56c4eaaec1
			defaultHierarchy: LocalDateTable_e9e054c1-8a5c-4b80-9684-b8717d11a0b7.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CODE Analytique'
		dataType: string
		lineageTag: f25743a4-a5ab-4de1-97aa-473b258c4d42
		summarizeBy: none
		sourceColumn: CODE Analytique

		annotation SummarizationSetBy = Automatic

	column 'Affectation Analytique '
		dataType: string
		lineageTag: 4f7ee1d4-fd27-4f3a-85d2-7741ec3e0eaf
		summarizeBy: none
		sourceColumn: "Affectation Analytique "

		annotation SummarizationSetBy = Automatic

	column 'Catégorie conventionnelle'
		dataType: string
		lineageTag: 20104fc5-33cd-4c5f-9ad8-a12d579fd7e7
		summarizeBy: none
		sourceColumn: Catégorie conventionnelle

		annotation SummarizationSetBy = Automatic

	column 'Type de contrat'
		dataType: string
		lineageTag: 9b4c5214-14f4-4e6e-a8b3-6fdf93d1ad47
		summarizeBy: none
		sourceColumn: Type de contrat

		annotation SummarizationSetBy = Automatic

	column 'Si CDD ou stagiaire, merci de préciser la date de fin de contrat'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc190bf3-0799-4c8b-ad2d-281b10bc1359
		summarizeBy: none
		sourceColumn: Si CDD ou stagiaire, merci de préciser la date de fin de contrat

		variation Variation
			isDefault
			relationship: c966726b-e6d4-451e-883f-7f940cda317f
			defaultHierarchy: LocalDateTable_43fafd8f-a8fe-4351-9250-43a39ba1e15f.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Statut Local ou Expatrié?'
		dataType: string
		lineageTag: 1e70d9c9-e3c1-4ab1-abca-665b93cbfe0a
		summarizeBy: none
		sourceColumn: Statut Local ou Expatrié?

		annotation SummarizationSetBy = Automatic

	column Nationalité
		dataType: string
		lineageTag: 4b482fcb-b98f-402d-bc1e-ddf25b9d41ad
		summarizeBy: none
		sourceColumn: Nationalité

		annotation SummarizationSetBy = Automatic

	column Ancienneté2
		dataType: int64
		formatString: 0
		lineageTag: 6af89cfe-8683-4072-9c5d-c3cac03c1f60
		summarizeBy: sum
		sourceColumn: Ancienneté2

		annotation SummarizationSetBy = Automatic

	column 'Tranche d''age'
		dataType: string
		lineageTag: 74c573f5-8f47-4571-98b8-e148549839ea
		summarizeBy: none
		sourceColumn: Tranche d'age

		annotation SummarizationSetBy = Automatic

	column 'Tranche d''ancienneté'
		dataType: string
		lineageTag: 203c9731-23ce-43d4-b9ae-22247fefd22e
		summarizeBy: none
		sourceColumn: Tranche d'ancienneté

		annotation SummarizationSetBy = Automatic

	partition Embauche = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    Embauche_Sheet = Source{[Item="Embauche",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Embauche_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Type d'entrée dans la société", type text}, {"Motif de recrutement", type text}, {"Société", type text}, {"Matricule", type any}, {"User ID", Int64.Type}, {"Nom", type text}, {"Prénom", type text}, {"Sexe", type text}, {"Date de naissance", type date}, {"Age", Int64.Type}, {"Date d'embauche", type date}, {"Direction", type text}, {"Département", type text}, {"Service", type text}, {"Poste harmonisé", type text}, {"Fonction", type text}, {"Date d'entrée", type date}, {"CODE Analytique", type text}, {"Affectation Analytique ", type text}, {"Catégorie conventionnelle", type text}, {"Type de contrat", type text}, {"Si CDD ou stagiaire, merci de préciser la date de fin de contrat", type date}, {"Statut Local ou Expatrié?", type text}, {"Nationalité", type text}, {"Ancienneté2", Int64.Type}, {"Tranche d'age", type text}, {"Tranche d'ancienneté", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

