table Recrutement
	lineageTag: 904189d1-694c-4b8d-a91f-bad8a2aeed1f

	measure 'Recruitments Count' = SUM(Recrutement[Recruitments])
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675526

	measure 'Recruitments Count Latest' =
			VAR _lastDate = CALCULATE(MAX(Recrutement[DATE]), ALL(Recrutement))
			RETURN CALCULATE([Recruitments Count], Recrutement[DATE] = _lastDate)
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: 8a53e9c1-4328-4123-b424-9481115a8573

	measure 'Recruitment Budget Used' = SUM(Recrutement[BudgetUsed])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: eeba9fe5-4d1c-4b4d-90eb-073061900fae

	measure 'Recruitment Budget Used Latest' =
			VAR _lastDate = CALCULATE(MAX(Recrutement[DATE]), ALL(Recrutement))
			RETURN CALCULATE([Recruitment Budget Used], Recrutement[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: 03fac29e-766c-4e72-83cb-c350c7c04c77

	measure 'Recruitments Budget Count' = SUM(Recrutement[RecruitmentsBudget])
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675527

	measure 'Recruitments Budget Count Latest' =
			VAR _lastDate = CALCULATE(MAX(Recrutement[DATE]), ALL(Recrutement))
			RETURN CALCULATE([Recruitments Budget Count], Recrutement[DATE] = _lastDate)
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675528

	measure 'Recruitment Budget' = SUM(Recrutement[RecruitmentBudget])
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675529

	measure 'Recruitment Budget Latest' =
			VAR _lastDate = CALCULATE(MAX(Recrutement[DATE]), ALL(Recrutement))
			RETURN CALCULATE([Recruitment Budget], Recrutement[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance'
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675530

	column DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86c4bfbe-c7f0-45e2-a469-b472c5692fbf
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Recruitments
		dataType: int64
		formatString: 0
		lineageTag: 52fc52c5-d983-48e7-b07b-569e746e5dba
		summarizeBy: sum
		sourceColumn: Recruitments

		annotation SummarizationSetBy = Automatic

	column BudgetUsed
		dataType: double
		lineageTag: 710e8676-26d9-447c-9be5-ea342e8833cf
		summarizeBy: sum
		sourceColumn: BudgetUsed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RecruitmentsBudget
		dataType: int64
		formatString: 0
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675531
		summarizeBy: sum
		sourceColumn: RecruitmentsBudget

		annotation SummarizationSetBy = Automatic

	column RecruitmentsOutOfBudget
		dataType: int64
		formatString: 0
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675532
		summarizeBy: sum
		sourceColumn: RecruitmentsOutOfBudget

		annotation SummarizationSetBy = Automatic

	column RecruitmentBudget
		dataType: double
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675533
		summarizeBy: sum
		sourceColumn: RecruitmentBudget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OutOfBudgetCost
		dataType: double
		lineageTag: db986fad-7b80-441b-8d60-5e3e89675534
		summarizeBy: sum
		sourceColumn: OutOfBudgetCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Recrutement = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    Recrutement_Sheet = Source{[Item="Recrutement",Kind="Sheet"]}[Data],
				    #"PromoteHeaders" = Table.PromoteHeaders(Recrutement_Sheet, [PromoteAllScalars=true]),
				    _cols = Table.ColumnNames(#"PromoteHeaders"),
				    #"KeepColumns" = Table.SelectColumns(#"PromoteHeaders", {_cols{0}, _cols{1}, _cols{2}, _cols{3}, _cols{4}, _cols{5}, _cols{6}}),
				    #"RenameColumns" = Table.RenameColumns(#"KeepColumns", {{_cols{0}, "DATE"}, {_cols{1}, "Recruitments"}, {_cols{2}, "RecruitmentsBudget"}, {_cols{3}, "RecruitmentsOutOfBudget"}, {_cols{4}, "RecruitmentBudget"}, {_cols{5}, "BudgetUsed"}, {_cols{6}, "OutOfBudgetCost"}}),
				    #"MonthlyRows" = Table.FirstN(#"RenameColumns", each (try Number.From([DATE]) otherwise null) <> null),
				    #"NormalizeDate" = Table.TransformColumns(#"MonthlyRows", {{"DATE", each Number.From(_), type number}}),
				    #"ConvertDate" = Table.TransformColumns(#"NormalizeDate", {{"DATE", each Date.AddDays(#date(1899, 12, 30), _), type date}}),
				    #"ChangedType" = Table.TransformColumnTypes(#"ConvertDate", {{"Recruitments", Int64.Type}, {"RecruitmentsBudget", Int64.Type}, {"RecruitmentsOutOfBudget", Int64.Type}, {"RecruitmentBudget", type number}, {"BudgetUsed", type number}, {"OutOfBudgetCost", type number}})
				in
				    #"ChangedType"

	annotation PBI_ResultType = Table

