table DIM_Nationalite
	lineageTag: f06bd671-e45b-4ca3-9859-de9ac537a59e

	column REF_Nationalite
		dataType: string
		lineageTag: 5986b88a-eabd-45e2-bd5f-8243cd3dda44
		sourceColumn: REF_Nationalite

	column Label
		dataType: string
		lineageTag: 1b7ed4f3-77b4-4db1-a62a-c97bc02b632e
		sourceColumn: Label

	partition DIM_Nationalite = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    RefTable = Source{[Item="tbl_REF_Nationalite",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(RefTable, {{"REF_Nationalite", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_Nationalite", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_Nationalite] <> null and [REF_Nationalite] <> ""),
				    #"DistinctRows" = Table.Distinct(#"FilteredRows"),
				    #"SortedRows" = Table.Sort(#"DistinctRows", {{"Label", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

