table DIM_AbsenceType
	lineageTag: 0dde9fee-8192-4124-8f00-42fd32021298

	column REF_AbsenceType
		dataType: string
		lineageTag: d37e2d60-e38b-4237-a0d6-ded876e46dd0
		sourceColumn: REF_AbsenceType

	column Label
		dataType: string
		lineageTag: 72bb283e-c1f6-4a76-9a17-8dbb9209f8ea
		sourceColumn: Label

	partition DIM_AbsenceType = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    RefTable = Source{[Item="tbl_REF_AbsenceType",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(RefTable, {{"REF_AbsenceType", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_AbsenceType", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_AbsenceType] <> null and [REF_AbsenceType] <> ""),
				    #"DistinctRows" = Table.Distinct(#"FilteredRows"),
				    #"SortedRows" = Table.Sort(#"DistinctRows", {{"Label", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

