table DIM_TCDPLevel
	lineageTag: ce1b869b-06af-4c11-88a9-06dbd4eeee94

	column REF_TCDPLevel
		dataType: string
		lineageTag: 78effd5c-ef49-41e4-96f6-460352679bc5
		sourceColumn: REF_TCDPLevel

	column Label
		dataType: string
		lineageTag: d3e7c4ec-4b34-4044-b4d5-e5c003e4bce7
		sourceColumn: Label

	column LevelOrder
		dataType: int64
		lineageTag: 58cea09a-5822-4b0b-a7e7-6f58290e07ac
		sourceColumn: LevelOrder

	partition DIM_TCDPLevel = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    RefTable = Source{[Item="tbl_REF_TCDPLevel",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(RefTable, {{"REF_TCDPLevel", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_TCDPLevel", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_TCDPLevel] <> null and [REF_TCDPLevel] <> ""),
				    #"AddedOrder" = Table.AddColumn(#"FilteredRows", "LevelOrder", each if [REF_TCDPLevel] = "L1" then 1 else if [REF_TCDPLevel] = "L2A" then 2 else if [REF_TCDPLevel] = "L2B" then 3 else if [REF_TCDPLevel] = "L2C" then 4 else if [REF_TCDPLevel] = "L3A" then 6 else if [REF_TCDPLevel] = "L3B" then 7 else if [REF_TCDPLevel] = "L3C" then 8 else if [REF_TCDPLevel] = "L4" then 9 else if [REF_TCDPLevel] = "L5" then 10 else 99, Int64.Type),
				    #"SortedRows" = Table.Sort(#"AddedOrder", {{"LevelOrder", Order.Ascending}, {"Label", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

