table DIM_CatConv
	lineageTag: 65bce5bf-6d7d-46b6-88a6-ffdc8f081a8f

	column REF_CatConv
		dataType: string
		lineageTag: 69cc0ca5-f287-4db1-9f85-4421520bb130
		sourceColumn: REF_CatConv

	column Label
		dataType: string
		lineageTag: 2a5104cc-bf90-4c7f-b5a2-162525dc2628
		sourceColumn: Label

	partition DIM_CatConv = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    RefTable = Source{[Item="tbl_REF_CatConv",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(RefTable, {{"REF_CatConv", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_CatConv", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_CatConv] <> null and [REF_CatConv] <> ""),
				    #"DistinctRows" = Table.Distinct(#"FilteredRows"),
				    #"SortedRows" = Table.Sort(#"DistinctRows", {{"Label", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

