table DIM_TypeContrat
	lineageTag: fac516d1-871c-4699-a772-6f170827c5a4

	column REF_TypeContrat
		dataType: string
		lineageTag: 40475cb1-433e-44e8-ae66-ea7daf65ccac
		sourceColumn: REF_TypeContrat

	column Label
		dataType: string
		lineageTag: 19eebf3b-f832-4285-af5b-4ed4b923a4cf
		sourceColumn: Label

	partition DIM_TypeContrat = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    RefTable = Source{[Item="tbl_REF_TypeContrat",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(RefTable, {{"REF_TypeContrat", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_TypeContrat", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_TypeContrat] <> null and [REF_TypeContrat] <> ""),
				    #"DistinctRows" = Table.Distinct(#"FilteredRows"),
				    #"SortedRows" = Table.Sort(#"DistinctRows", {{"Label", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

