table Embauches
	lineageTag: 770abfbf-2ee3-47f7-a3e2-584ea427b141

	column FilialeCode
		dataType: string
		lineageTag: 4be12db3-4d66-4dd0-8ce8-87d0e18a0a64
		summarizeBy: none
		sourceColumn: FilialeCode

		annotation SummarizationSetBy = Automatic

	column FilialeName
		dataType: string
		lineageTag: 07d68e51-a5b0-4c98-a4d6-f0aa311ded66
		summarizeBy: none
		sourceColumn: FilialeName

		annotation SummarizationSetBy = Automatic

	column EventDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 480055f4-9702-4b98-9d42-6493b508ea06
		summarizeBy: none
		sourceColumn: EventDate

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c86528c4-9173-42e2-9383-5f1a1ae1c044
		summarizeBy: none
		sourceColumn: MonthStartDate

		variation Variation
			isDefault
			relationship: fedf1cfd-6f1f-4254-8d11-04565797ffb0
			defaultHierarchy: LocalDateTable_3b66c3d3-1f29-4452-9043-bcb263360977.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column SourceYear
		dataType: int64
		lineageTag: c81344c2-92cd-487d-8430-e0881d9a223b
		summarizeBy: sum
		sourceColumn: SourceYear

		annotation SummarizationSetBy = Automatic

	column Matricule
		dataType: string
		lineageTag: 454a4f0a-5eb5-4c5d-902d-3747572efc6b
		summarizeBy: none
		sourceColumn: Matricule

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: string
		lineageTag: 60338f4f-8d9a-4972-8673-f93caa1a5934
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column UserID
		dataType: int64
		lineageTag: bfd33670-b347-4743-9463-d1c44d8c21af
		summarizeBy: count
		sourceColumn: UserID

		annotation SummarizationSetBy = Automatic

	column Nom
		dataType: string
		lineageTag: 4df815d8-124f-481d-b5f2-79b7e6166d77
		summarizeBy: none
		sourceColumn: Nom

		annotation SummarizationSetBy = Automatic

	column Prenom
		dataType: string
		lineageTag: bfc866e6-db5d-4627-9abe-610816d66280
		summarizeBy: none
		sourceColumn: Prenom

		annotation SummarizationSetBy = Automatic

	column SexeCode
		dataType: string
		lineageTag: 65f4af97-d046-45e8-9cf5-c3c88e709d00
		summarizeBy: none
		sourceColumn: SexeCode

		annotation SummarizationSetBy = Automatic

	column DateNaissance
		dataType: dateTime
		formatString: Long Date
		lineageTag: 142c676a-cc24-4387-b01b-f30666e24df6
		summarizeBy: none
		sourceColumn: DateNaissance

		variation Variation
			isDefault
			relationship: e3d13400-9ce3-4491-8b34-94a05f6fe114
			defaultHierarchy: LocalDateTable_510882d2-74d9-470e-9173-340bad687ab7.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column DateEmbauche
		dataType: dateTime
		formatString: Long Date
		lineageTag: 91068470-0b49-4b11-adc0-dd78686fd72b
		summarizeBy: none
		sourceColumn: DateEmbauche

		variation Variation
			isDefault
			relationship: 086f8310-3376-49fe-8fa1-3338fa73aad7
			defaultHierarchy: LocalDateTable_1771491a-6727-4d9e-82ea-ea431f298f79.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column DateEntree
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c16100e-4460-46ca-9dc2-5860025669df
		summarizeBy: none
		sourceColumn: DateEntree

		variation Variation
			isDefault
			relationship: a749a049-cabe-4598-9c2e-52f2c424437e
			defaultHierarchy: LocalDateTable_ec58d15d-8370-47cf-85b7-22119ee7c5ab.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column TypeEntreeSocieteCode
		dataType: string
		lineageTag: 8cbfbe49-07cc-41dc-9325-1ce5c1cab40b
		summarizeBy: none
		sourceColumn: TypeEntreeSocieteCode

		annotation SummarizationSetBy = Automatic

	column MotifRecrutementCode
		dataType: string
		lineageTag: a66ee521-cb39-480f-822b-134e19cfc75c
		summarizeBy: none
		sourceColumn: MotifRecrutementCode

		annotation SummarizationSetBy = Automatic

	column Direction
		dataType: string
		lineageTag: 34ed136b-56f1-4be6-95bd-e059e65f73c6
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column Departement
		dataType: string
		lineageTag: ba30cd7c-4d46-4e6c-b8ba-915a0366a011
		summarizeBy: none
		sourceColumn: Departement

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: ec5bb4d6-f80d-4618-83a3-68f39b236b54
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column PosteHarmonise
		dataType: string
		lineageTag: 78a52b85-7e2f-4509-b9c2-e6fbeeffb4cc
		summarizeBy: none
		sourceColumn: PosteHarmonise

		annotation SummarizationSetBy = Automatic

	column Fonction
		dataType: string
		lineageTag: 6b9debfd-1261-4239-b66f-d9468b1b13a8
		summarizeBy: none
		sourceColumn: Fonction

		annotation SummarizationSetBy = Automatic

	column CodeAnalytique
		dataType: string
		lineageTag: b13840fc-cd84-476a-bd47-3183173bc900
		summarizeBy: none
		sourceColumn: CodeAnalytique

		annotation SummarizationSetBy = Automatic

	column AffectationAnalytique
		dataType: string
		lineageTag: fda14c4e-c8e3-4657-a149-003f944946a4
		summarizeBy: none
		sourceColumn: AffectationAnalytique

		annotation SummarizationSetBy = Automatic

	column CategorieConventionnelleCode
		dataType: string
		lineageTag: be30b50a-c8a6-4f57-af60-040530ea101c
		summarizeBy: none
		sourceColumn: CategorieConventionnelleCode

		annotation SummarizationSetBy = Automatic

	column TypeContratCode
		dataType: string
		lineageTag: be8d2850-edc7-43a0-81ba-21afdd695e36
		summarizeBy: none
		sourceColumn: TypeContratCode

		annotation SummarizationSetBy = Automatic

	column DateFinContrat
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5cc80258-1ed1-46dd-847b-b839085c637b
		summarizeBy: none
		sourceColumn: DateFinContrat

		variation Variation
			isDefault
			relationship: 5cb7ac89-df31-4589-a94c-b94d1b589083
			defaultHierarchy: LocalDateTable_8ea25b3c-ef8f-4128-84e3-7c4198f99a16.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column StatutGeoCode
		dataType: string
		lineageTag: b66223e8-5267-44b1-98b2-49b4e2d98797
		summarizeBy: none
		sourceColumn: StatutGeoCode

		annotation SummarizationSetBy = Automatic

	column NationaliteCode
		dataType: string
		lineageTag: f3cb4b85-c502-4f63-90ab-547f6ccfe242
		summarizeBy: none
		sourceColumn: NationaliteCode

		annotation SummarizationSetBy = Automatic

	column NiveauTCDPCode
		dataType: string
		lineageTag: 9a5dfe50-839c-4150-8245-6ac4fcee03ec
		summarizeBy: none
		sourceColumn: NiveauTCDPCode

		annotation SummarizationSetBy = Automatic

	partition Embauches = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    EmbauchesTable = Source{[Item="tbl_Embauches",Kind="Table"]}[Data],
				    #"FilteredRows" = Table.SelectRows(EmbauchesTable, each let _userId = try Text.Trim(Text.From([UserID])) otherwise "" in _userId <> ""),
				    ToDate = (value as any) as nullable date =>
				        let
				            DirectDate = try Date.From(value) otherwise null,
				            Serial = if DirectDate <> null then null else try Number.From(value) otherwise null
				        in
				            if DirectDate <> null then DirectDate else if Serial <> null then Date.AddDays(#date(1899, 12, 30), Serial) else null,
				    #"ConvertDates" = Table.TransformColumns(#"FilteredRows", {{"EventDate", ToDate, type date}, {"MonthStartDate", ToDate, type date}, {"DateNaissance", ToDate, type date}, {"DateEmbauche", ToDate, type date}, {"DateEntree", ToDate, type date}, {"DateFinContrat", ToDate, type date}}),
				    TextColumns = {"FilialeCode", "FilialeName", "Matricule", "Nom", "Prenom", "SexeCode", "TypeEntreeSocieteCode", "MotifRecrutementCode", "Direction", "Departement", "Service", "PosteHarmonise", "Fonction", "CodeAnalytique", "AffectationAnalytique", "CategorieConventionnelleCode", "TypeContratCode", "StatutGeoCode", "NationaliteCode", "NiveauTCDPCode"},
				    #"TrimmedText" = Table.TransformColumns(#"ConvertDates", List.Transform(TextColumns, each {_, (v) => if v = null then null else Text.Trim(Text.From(v)), type text})),
				    #"ChangedNumericTypes" = Table.TransformColumns(#"TrimmedText", {{"SourceYear", each try Int64.From(_) otherwise null, Int64.Type}, {"UserID", each try Int64.From(_) otherwise null, Int64.Type}}),
				    #"AddEmployeeKey" = Table.AddColumn(#"ChangedNumericTypes", "EmployeeKey", each if [FilialeCode] = null or [Matricule] = null or [Matricule] = "" then null else [FilialeCode] & "_" & [Matricule], type text),
				    #"SelectOutput" = Table.SelectColumns(#"AddEmployeeKey", {"FilialeCode", "FilialeName", "EventDate", "MonthStartDate", "SourceYear", "Matricule", "EmployeeKey", "UserID", "Nom", "Prenom", "SexeCode", "DateNaissance", "DateEmbauche", "DateEntree", "TypeEntreeSocieteCode", "MotifRecrutementCode", "Direction", "Departement", "Service", "PosteHarmonise", "Fonction", "CodeAnalytique", "AffectationAnalytique", "CategorieConventionnelleCode", "TypeContratCode", "DateFinContrat", "StatutGeoCode", "NationaliteCode", "NiveauTCDPCode"})
				in
				    #"SelectOutput"

	annotation PBI_ResultType = Table

