table 'Masse salariale'
	lineageTag: 5056f410-0785-4e07-8e63-cad4a7f3c499

	measure 'Payroll Amount' = SUM('Masse salariale'[Payroll])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ab

	measure 'Payroll Amount Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Payroll Amount], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: 620ddca3-0cde-4da7-8eb8-6f2c21f6aaa8

	measure 'Payroll HUB' = SUM('Masse salariale'[PayrollHUB])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b5808d2f-bde5-405f-a29f-b49ece52f6a0

	measure 'HUB Share' = DIVIDE([Payroll HUB], [Payroll Amount], 0)
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: 8141de85-a233-4ce0-bb73-9a0941e7196a

	measure 'HUB Share Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([HUB Share], 'Masse salariale'[DATE] = _lastDate)
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: 6b27faea-7ba8-4253-a837-220161d07900

	measure 'Overtime Hours' = SUM('Masse salariale'[OvertimeHours])
		formatString: 0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: e0829d63-f6a5-440d-bfa4-66b4016dc407

	measure 'Overtime Hours Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Overtime Hours], 'Masse salariale'[DATE] = _lastDate)
		formatString: 0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: c427f122-fbc0-4a34-aa7b-649a7aa7268e

	measure 'Payroll Budget' = SUM('Masse salariale'[PayrollBudget])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ac

	measure 'Payroll Budget Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Payroll Budget], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ad

	measure 'Overtime Cost' = SUM('Masse salariale'[OvertimeCost])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b2

	measure 'Leave Balance' = SUM('Masse salariale'[LeaveBalance])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ae

	measure 'Leave Balance Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Leave Balance], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8af

	measure 'Leave Provision' = SUM('Masse salariale'[LeaveProvision])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b0

	measure 'Leave Provision Latest' =
			VAR _lastDate = CALCULATE(MAX('Masse salariale'[DATE]), ALL('Masse salariale'))
			RETURN CALCULATE([Leave Provision], 'Masse salariale'[DATE] = _lastDate)
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b1

	measure 'Leave Provision Budget Proxy Latest' = [Payroll Budget Latest]
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b7

	measure 'Leave Provision Scenario Value' =
			VAR _scenario = SELECTEDVALUE(Scenario[Scenario], "Realise")
			RETURN IF(_scenario = "Budget", [Leave Provision Budget Proxy Latest], [Leave Provision Latest])
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b8

	measure 'Leave Provision Budget Proxy' = [Payroll Budget]
		formatString: #,0
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c0

	measure 'Staff Cost Consumed %' = DIVIDE([Payroll Amount Latest], [Payroll Budget Latest])
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b9

	measure 'Leave Provision Consumed %' = DIVIDE([Leave Provision Latest], [Leave Provision Budget Proxy Latest])
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8ba

	measure 'Staff Cost Consumed (Context) %' = DIVIDE([Payroll Amount], [Payroll Budget])
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c1

	measure 'Leave Provision Consumed (Context) %' = DIVIDE([Leave Provision], [Leave Provision Budget Proxy])
		formatString: 0.0%
		displayFolder: 'HR Performance\Payroll'
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8c2

	column DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c88bf51-a80b-409b-afb4-e70f11c363b1
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Payroll
		dataType: int64
		formatString: 0
		lineageTag: c3e97ec2-8fd0-46d5-902a-b030bcce154e
		summarizeBy: sum
		sourceColumn: Payroll

		annotation SummarizationSetBy = Automatic

	column PayrollHUB
		dataType: int64
		formatString: 0
		lineageTag: 16188af8-f003-4868-9692-258952ad368f
		summarizeBy: sum
		sourceColumn: PayrollHUB

		annotation SummarizationSetBy = Automatic

	column HUBShare
		dataType: double
		lineageTag: 27b6d541-75fd-47d7-bc1d-475f67c68eac
		summarizeBy: sum
		sourceColumn: HUBShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OvertimeHours
		dataType: double
		lineageTag: fa2162e2-1240-414f-956e-5de43015896a
		summarizeBy: sum
		sourceColumn: OvertimeHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayrollBudget
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b3
		summarizeBy: sum
		sourceColumn: PayrollBudget

		annotation SummarizationSetBy = Automatic

	column OvertimeCost
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b4
		summarizeBy: sum
		sourceColumn: OvertimeCost

		annotation SummarizationSetBy = Automatic

	column LeaveBalance
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b5
		summarizeBy: sum
		sourceColumn: LeaveBalance

		annotation SummarizationSetBy = Automatic

	column LeaveProvision
		dataType: int64
		formatString: 0
		lineageTag: b122239f-3f99-41b6-a60a-16575b2db8b6
		summarizeBy: sum
		sourceColumn: LeaveProvision

		annotation SummarizationSetBy = Automatic

	partition 'Masse salariale' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    Payroll_Table = Source{[Item="tbl_MasseSalarialeMensuelle",Kind="Table"]}[Data],
				    #"FilteredRows" = Table.SelectRows(Payroll_Table, each let _month = try Text.Trim(Text.From([MonthStartDate])) otherwise "" in _month <> ""),
				    ToDate = (value as any) as nullable date =>
				        let
				            _directDate = try Date.From(value) otherwise null,
				            _serial = if _directDate <> null then null else try Number.From(value) otherwise null
				        in
				            if _directDate <> null then _directDate else if _serial <> null then Date.AddDays(#date(1899, 12, 30), _serial) else null,
				    #"ConvertDate" = Table.TransformColumns(#"FilteredRows", {{"MonthStartDate", ToDate, type date}}),
				    #"SelectColumns" = Table.SelectColumns(#"ConvertDate", {"MonthStartDate", "PayrollBudget", "Payroll", "PayrollHUB", "OvertimeHours", "OvertimeCost", "LeaveBalance", "LeaveProvision"}),
				    #"RenamedColumns" = Table.RenameColumns(#"SelectColumns", {{"MonthStartDate", "DATE"}}),
				    #"ChangedType" = Table.TransformColumns(#"RenamedColumns", {{"PayrollBudget", each try Int64.From(_) otherwise null, Int64.Type}, {"Payroll", each try Int64.From(_) otherwise null, Int64.Type}, {"PayrollHUB", each try Int64.From(_) otherwise null, Int64.Type}, {"OvertimeHours", each try Number.From(_) otherwise null, type number}, {"OvertimeCost", each try Int64.From(_) otherwise null, Int64.Type}, {"LeaveBalance", each try Int64.From(_) otherwise null, Int64.Type}, {"LeaveProvision", each try Int64.From(_) otherwise null, Int64.Type}}),
				    #"HUBShareAdded" = Table.AddColumn(#"ChangedType", "HUBShare", each if [Payroll] = null or [Payroll] = 0 then 0 else Number.From([PayrollHUB]) / Number.From([Payroll]), type number)
				in
				    #"HUBShareAdded"

	annotation PBI_ResultType = Table

