table 'TCDP Level Dim'
	lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8231

	column Level
		dataType: string
		lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8232
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column 'Level Order'
		dataType: int64
		formatString: 0
		lineageTag: 4cf2a1e9-ea32-4744-96cb-0a8c4a6b8233
		summarizeBy: sum
		sourceColumn: Level Order

		annotation SummarizationSetBy = Automatic

	partition 'TCDP Level Dim' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    TCDPLevel_Table = Source{[Item="tbl_REF_TCDPLevel",Kind="Table"]}[Data],
				    #"ChangedType" = Table.TransformColumnTypes(TCDPLevel_Table, {{"REF_TCDPLevel", type text}, {"Label", type text}}),
				    #"TrimmedText" = Table.TransformColumns(#"ChangedType", {{"REF_TCDPLevel", each if _ = null then null else Text.Trim(_), type text}, {"Label", each if _ = null then null else Text.Trim(_), type text}}),
				    #"FilteredRows" = Table.SelectRows(#"TrimmedText", each [REF_TCDPLevel] <> null and [REF_TCDPLevel] <> ""),
				    #"RenamedColumns" = Table.RenameColumns(#"FilteredRows", {{"Label", "Level"}}),
				    #"AddedCustom" = Table.AddColumn(#"RenamedColumns", "Level Order", each if [REF_TCDPLevel] = "L1" then 1 else if [REF_TCDPLevel] = "L2A" then 2 else if [REF_TCDPLevel] = "L2B" then 3 else if [REF_TCDPLevel] = "L2C" then 4 else if [REF_TCDPLevel] = "L3A" then 6 else if [REF_TCDPLevel] = "L3B" then 7 else if [REF_TCDPLevel] = "L3C" then 8 else if [REF_TCDPLevel] = "L4" then 9 else if [REF_TCDPLevel] = "L5" then 10 else 99, Int64.Type),
				    #"SelectColumns" = Table.SelectColumns(#"AddedCustom", {"Level", "Level Order"}),
				    #"SortedRows" = Table.Sort(#"SelectColumns", {{"Level Order", Order.Ascending}, {"Level", Order.Ascending}})
				in
				    #"SortedRows"

	annotation PBI_ResultType = Table

