table 'TCDP Gender'
	lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa01

	measure 'TCDP Men' = SUM('TCDP Gender'[MenCount])
		formatString: 0
		displayFolder: 'TCDP\Diversity'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa02

	measure 'TCDP Women' = SUM('TCDP Gender'[WomenCount])
		formatString: 0
		displayFolder: 'TCDP\Diversity'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa03

	measure 'TCDP Men Latest' =
			VAR _lastMonth = MAXX(ALL('TCDP Gender'), 'TCDP Gender'[MonthOrder])
			RETURN COALESCE(CALCULATE([TCDP Men], 'TCDP Gender'[MonthOrder] = _lastMonth), 0)
		formatString: 0
		displayFolder: 'TCDP\Diversity'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa04

	measure 'TCDP Women Latest' =
			VAR _lastMonth = MAXX(ALL('TCDP Gender'), 'TCDP Gender'[MonthOrder])
			RETURN COALESCE(CALCULATE([TCDP Women], 'TCDP Gender'[MonthOrder] = _lastMonth), 0)
		formatString: 0
		displayFolder: 'TCDP\Diversity'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa05

	measure 'TCDP Diversity Rate' = DIVIDE([TCDP Women Latest], [TCDP Men Latest] + [TCDP Women Latest])
		formatString: 0.0%
		displayFolder: 'TCDP\Diversity'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa0b

	column Mois
		dataType: string
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa06
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

	column MonthOrder
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa07
		summarizeBy: sum
		sourceColumn: MonthOrder

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa08
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column MenCount
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa09
		summarizeBy: sum
		sourceColumn: MenCount

		annotation SummarizationSetBy = Automatic

	column WomenCount
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa0a
		summarizeBy: sum
		sourceColumn: WomenCount

		annotation SummarizationSetBy = Automatic

	partition 'TCDP Gender' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FolderPathParameter & "\" & SourceWorkbookNameParameter), null, true),
				    TCDP_Table = Source{[Item="tbl_TCDP_Genre",Kind="Table"]}[Data],
				    #"FilteredRows" = Table.SelectRows(TCDP_Table, each let _month = try Text.Trim(Text.From([MonthStartDate])) otherwise "" in _month <> ""),
				    ToDate = (value as any) as nullable date =>
				        let
				            _directDate = try Date.From(value) otherwise null,
				            _serial = if _directDate <> null then null else try Number.From(value) otherwise null
				        in
				            if _directDate <> null then _directDate else if _serial <> null then Date.AddDays(#date(1899, 12, 30), _serial) else null,
				    LevelMap = [L1 = "Level 1", L2A = "Level 2A", L2B = "Level 2B", L2C = "Level 2C", L3A = "Level 3A", L3B = "Level 3B", L3C = "Level 3C", L4 = "Level 4", L5 = "Level 5"],
				    MapValue = (value as any, mapping as record) as nullable text =>
				        let
				            _key = if value = null then null else Text.Trim(Text.From(value))
				        in
				            if _key = null or _key = "" then null else try Record.Field(mapping, _key) otherwise _key,
				    #"ConvertDate" = Table.TransformColumns(#"FilteredRows", {{"MonthStartDate", ToDate, type date}}),
				    #"SelectColumns" = Table.SelectColumns(#"ConvertDate", {"MonthStartDate", "TCDPLevelCode", "MenCount", "WomenCount"}),
				    #"RenamedColumns" = Table.RenameColumns(#"SelectColumns", {{"TCDPLevelCode", "Level"}}),
				    #"MappedLevels" = Table.TransformColumns(#"RenamedColumns", {{"Level", each MapValue(_, LevelMap), type text}, {"MenCount", each try Int64.From(_) otherwise null, Int64.Type}, {"WomenCount", each try Int64.From(_) otherwise null, Int64.Type}}),
				    #"AddMonthLabel" = Table.AddColumn(#"MappedLevels", "Mois", each Date.ToText([MonthStartDate], "MMM-yy", "fr-FR"), type text),
				    #"AddMonthOrder" = Table.AddColumn(#"AddMonthLabel", "MonthOrder", each Date.Year([MonthStartDate]) * 100 + Date.Month([MonthStartDate]), Int64.Type),
				    #"SelectOutput" = Table.SelectColumns(#"AddMonthOrder", {"Mois", "MonthOrder", "Level", "MenCount", "WomenCount"})
				in
				    #"SelectOutput"

	annotation PBI_ResultType = Table

