table Absence
	lineageTag: b21b09b9-e76d-4319-b938-1ead84c4dd47

	measure 'Absence Rate' = AVERAGE(Absence[AbsenceRate])
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: 3e31c83c-ba60-42ad-ab39-f15609be783b

	measure 'Absence Rate Latest' =
			VAR _lastDate = CALCULATE(MAX(Absence[DATE]), ALL(Absence))
			RETURN CALCULATE([Absence Rate], Absence[DATE] = _lastDate)
		formatString: 0.0%
		displayFolder: 'HR Performance'
		lineageTag: d369c464-4492-452f-8c8b-00977551e6c7

	measure 'Absence Hours' = SUM(Absence[AbsenceHours])
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589a

	measure 'Absence Hours Latest' =
			VAR _lastDate = CALCULATE(MAX(Absence[DATE]), ALL(Absence))
			RETURN CALCULATE([Absence Hours], Absence[DATE] = _lastDate)
		formatString: 0
		displayFolder: 'HR Performance'
		lineageTag: bfcdc5fc-baa7-4d2f-80eb-4bdde7123ab2

	measure 'Leave Days Taken' = SUM(Absence[LeaveDaysTaken])
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: db15e180-6cd2-4d34-b396-eebbc5ec9492

	measure 'Leave Days Taken Latest' =
			VAR _lastDate = CALCULATE(MAX(Absence[DATE]), ALL(Absence))
			RETURN CALCULATE([Leave Days Taken], Absence[DATE] = _lastDate)
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: 8af51763-4246-4b07-8fa3-446b2edf8efc

	measure 'Leave Days Opening' = SUM(Absence[OpeningLeaveDays])
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589b

	measure 'Leave Days Opening Latest' =
			VAR _lastDate = CALCULATE(MAX(Absence[DATE]), ALL(Absence))
			RETURN CALCULATE([Leave Days Opening], Absence[DATE] = _lastDate)
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589c

	measure 'Leave Days Closing' = SUM(Absence[ClosingLeaveDays])
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589d

	measure 'Leave Days Closing Latest' =
			VAR _lastDate = CALCULATE(MAX(Absence[DATE]), ALL(Absence))
			RETURN CALCULATE([Leave Days Closing], Absence[DATE] = _lastDate)
		formatString: 0.0
		displayFolder: 'HR Performance'
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589e

	column DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3d773332-2c3d-476f-8f0a-4e58c49ef4d8
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeaveDaysTaken
		dataType: double
		lineageTag: c40e0eb5-a9bc-45f8-bddc-a396e4dbdfd0
		summarizeBy: sum
		sourceColumn: LeaveDaysTaken

		annotation SummarizationSetBy = Automatic

	column AbsenceHours
		dataType: int64
		formatString: 0
		lineageTag: a80ec9bd-7097-4fc3-851f-1ad4c0d7787e
		summarizeBy: sum
		sourceColumn: AbsenceHours

		annotation SummarizationSetBy = Automatic

	column AbsenceRate
		dataType: double
		lineageTag: 3e76b205-0267-4e3f-a531-c7058b324c33
		summarizeBy: sum
		sourceColumn: AbsenceRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OpeningLeaveDays
		dataType: double
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f5589f
		summarizeBy: sum
		sourceColumn: OpeningLeaveDays

		annotation SummarizationSetBy = Automatic

	column LeaveDaysAccrued
		dataType: double
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f558a0
		summarizeBy: sum
		sourceColumn: LeaveDaysAccrued

		annotation SummarizationSetBy = Automatic

	column ClosingLeaveDays
		dataType: double
		lineageTag: 5fba9a7a-b402-43f4-99ab-b4ac65f558a1
		summarizeBy: sum
		sourceColumn: ClosingLeaveDays

		annotation SummarizationSetBy = Automatic

	partition Absence = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    Absence_Sheet = Source{[Item="Absence",Kind="Sheet"]}[Data],
				    #"SkipTopRow" = Table.Skip(Absence_Sheet, 1),
				    #"PromoteHeaders" = Table.PromoteHeaders(#"SkipTopRow", [PromoteAllScalars=true]),
				    _cols = Table.ColumnNames(#"PromoteHeaders"),
				    #"KeepColumns" = Table.SelectColumns(#"PromoteHeaders", {_cols{0}, _cols{1}, _cols{2}, _cols{3}, _cols{4}, _cols{5}, _cols{6}}),
				    #"RenameColumns" = Table.RenameColumns(#"KeepColumns", {{_cols{0}, "DATE"}, {_cols{1}, "OpeningLeaveDays"}, {_cols{2}, "LeaveDaysTaken"}, {_cols{3}, "LeaveDaysAccrued"}, {_cols{4}, "ClosingLeaveDays"}, {_cols{5}, "AbsenceHours"}, {_cols{6}, "AbsenceRate"}}),
				    #"FilterRows" = Table.SelectRows(#"RenameColumns", each (try Number.From([DATE]) otherwise null) <> null),
				    #"ConvertDate" = Table.TransformColumns(#"FilterRows", {{"DATE", each Date.AddDays(#date(1899, 12, 30), Number.From(_)), type date}}),
				    #"ChangedType" = Table.TransformColumnTypes(#"ConvertDate", {{"OpeningLeaveDays", type number}, {"LeaveDaysTaken", type number}, {"LeaveDaysAccrued", type number}, {"ClosingLeaveDays", type number}, {"AbsenceHours", Int64.Type}, {"AbsenceRate", type number}})
				in
				    #"ChangedType"

	annotation PBI_ResultType = Table

