table 'TCDP Levels'
	lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63201

	measure 'TCDP Level Headcount' = SUM('TCDP Levels'[Headcount])
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63202

	measure 'TCDP Level Headcount Latest' =
			VAR _lastMonth = MAXX(ALL('TCDP Levels'), 'TCDP Levels'[MonthOrder])
			RETURN CALCULATE([TCDP Level Headcount], 'TCDP Levels'[MonthOrder] = _lastMonth)
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63203

	column Mois
		dataType: string
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63204
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

	column MonthOrder
		dataType: int64
		formatString: 0
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63205
		summarizeBy: sum
		sourceColumn: MonthOrder

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63206
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column Headcount
		dataType: int64
		formatString: 0
		lineageTag: e7eb91a1-c4d1-40ab-82a7-5e487fb63207
		summarizeBy: sum
		sourceColumn: Headcount

		annotation SummarizationSetBy = Automatic

	partition 'TCDP Levels' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    TCDP_Sheet = Source{[Item="TCDP",Kind="Sheet"]}[Data],
				    #"SkipTopRow" = Table.Skip(TCDP_Sheet, 1),
				    #"PromoteHeaders" = Table.PromoteHeaders(#"SkipTopRow", [PromoteAllScalars=true]),
				    _cols = Table.ColumnNames(#"PromoteHeaders"),
				    #"KeepColumns" = Table.SelectColumns(#"PromoteHeaders", {_cols{0}, _cols{1}, _cols{5}, _cols{6}, _cols{7}, _cols{8}}),
				    #"RenameColumns" = Table.RenameColumns(#"KeepColumns", {{_cols{0}, "DATE"}, {_cols{1}, "Level 1"}, {_cols{5}, "Level 3A"}, {_cols{6}, "Level 3B"}, {_cols{7}, "Level 3C"}, {_cols{8}, "Level 4"}}),
				    #"MonthlyRows" = Table.FirstN(#"RenameColumns", each (try Number.From([DATE]) otherwise null) <> null),
				    #"NormalizeDate" = Table.TransformColumns(#"MonthlyRows", {{"DATE", each Number.From(_), type number}}),
				    #"ConvertDate" = Table.TransformColumns(#"NormalizeDate", {{"DATE", each Date.AddDays(#date(1899, 12, 30), _), type date}}),
				    #"ChangedType" = Table.TransformColumnTypes(#"ConvertDate", {{"Level 1", Int64.Type}, {"Level 3A", Int64.Type}, {"Level 3B", Int64.Type}, {"Level 3C", Int64.Type}, {"Level 4", Int64.Type}}),
				    #"Unpivoted" = Table.UnpivotOtherColumns(#"ChangedType", {"DATE"}, "Level", "Headcount"),
				    #"AddMonthLabel" = Table.AddColumn(#"Unpivoted", "Mois", each Date.ToText([DATE], "MMM-yy", "fr-FR"), type text),
				    #"AddMonthOrder" = Table.AddColumn(#"AddMonthLabel", "MonthOrder", each Date.Year([DATE]) * 100 + Date.Month([DATE]), Int64.Type),
				    #"SelectOutput" = Table.SelectColumns(#"AddMonthOrder", {"Mois", "MonthOrder", "Level", "Headcount"})
				in
				    #"SelectOutput"

	annotation PBI_ResultType = Table

