table 'TCDP Gender'
	lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa01

	measure 'TCDP Men' = SUM('TCDP Gender'[MenCount])
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa02

	measure 'TCDP Women' = SUM('TCDP Gender'[WomenCount])
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa03

	measure 'TCDP Men Latest' =
			VAR _lastMonth = MAXX(ALL('TCDP Gender'), 'TCDP Gender'[MonthOrder])
			RETURN COALESCE(CALCULATE([TCDP Men], 'TCDP Gender'[MonthOrder] = _lastMonth), 0)
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa04

	measure 'TCDP Women Latest' =
			VAR _lastMonth = MAXX(ALL('TCDP Gender'), 'TCDP Gender'[MonthOrder])
			RETURN COALESCE(CALCULATE([TCDP Women], 'TCDP Gender'[MonthOrder] = _lastMonth), 0)
		formatString: 0
		displayFolder: 'TCDP'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa05

	measure 'TCDP Diversity Rate' = DIVIDE([TCDP Women Latest], [TCDP Men Latest] + [TCDP Women Latest])
		formatString: 0.0%
		displayFolder: 'TCDP'
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa0b

	column Mois
		dataType: string
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa06
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

	column MonthOrder
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa07
		summarizeBy: sum
		sourceColumn: MonthOrder

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa08
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column MenCount
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa09
		summarizeBy: sum
		sourceColumn: MenCount

		annotation SummarizationSetBy = Automatic

	column WomenCount
		dataType: int64
		formatString: 0
		lineageTag: 24860526-b7ef-4c85-b0c0-b4ea7c4efa0a
		summarizeBy: sum
		sourceColumn: WomenCount

		annotation SummarizationSetBy = Automatic

	partition 'TCDP Gender' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    TCDP_Sheet = Source{[Item="TCDP",Kind="Sheet"]}[Data],
				    #"SkipToDetail" = Table.Skip(TCDP_Sheet, 20),
				    #"PromoteHeaders" = Table.PromoteHeaders(#"SkipToDetail", [PromoteAllScalars=true]),
				    #"KeepColumns" = Table.SelectColumns(#"PromoteHeaders", {"Mois", "Hommes", "Femmes"}),
				    #"FilteredRows" = Table.SelectRows(#"KeepColumns", each [Hommes] <> null and Text.Trim(Text.From([Hommes])) <> ""),
				    #"AddLevel" = Table.AddColumn(#"FilteredRows", "Level", each let _raw = Text.Upper(Text.Trim(Text.BeforeDelimiter(Text.From([Hommes]), "="))) in if _raw = "N4" then "Level 4" else if _raw = "N3C" then "Level 3C" else if _raw = "N3B" then "Level 3B" else if _raw = "N3A" then "Level 3A" else if _raw = "N1" then "Level 1" else _raw, type text),
				    #"AddMenCount" = Table.AddColumn(#"AddLevel", "MenCount", each Number.FromText(Text.Select(Text.AfterDelimiter(Text.From([Hommes]), "="), {"0".."9"})), Int64.Type),
				    #"AddWomenCount" = Table.AddColumn(#"AddMenCount", "WomenCount", each Number.FromText(Text.Select(Text.AfterDelimiter(Text.From([Femmes]), "="), {"0".."9"})), Int64.Type),
				    #"AddMonthDate" = Table.AddColumn(#"AddWomenCount", "MonthDate", each Date.FromText("01-" & Text.From([Mois]), [Culture = "fr-FR"]), type date),
				    #"AddMonthOrder" = Table.AddColumn(#"AddMonthDate", "MonthOrder", each Date.Year([MonthDate]) * 100 + Date.Month([MonthDate]), Int64.Type),
				    #"SelectOutput" = Table.SelectColumns(#"AddMonthOrder", {"Mois", "MonthOrder", "Level", "MenCount", "WomenCount"})
				in
				    #"SelectOutput"

	annotation PBI_ResultType = Table

