table Tableau24
	lineageTag: faeb95b3-bde8-4d4c-8bbe-07015dda5b37

	column 'Type d''entrée dans la société'
		dataType: string
		lineageTag: a735a75b-85de-4981-a8ec-f31b5f25d64c
		summarizeBy: none
		sourceColumn: Type d'entrée dans la société

		annotation SummarizationSetBy = Automatic

	column 'Motif de recrutement'
		dataType: string
		lineageTag: 55a4414f-37b2-493f-bb00-f7f6bb336820
		summarizeBy: none
		sourceColumn: Motif de recrutement

		annotation SummarizationSetBy = Automatic

	column Société
		dataType: string
		lineageTag: 577920be-4236-4aa8-8c6d-7ee919da30cf
		summarizeBy: none
		sourceColumn: Société

		annotation SummarizationSetBy = Automatic

	column Matricule
		dataType: string
		lineageTag: c729900b-4bc1-47fd-8573-a1b178629a0d
		summarizeBy: none
		sourceColumn: Matricule

		annotation SummarizationSetBy = Automatic

	column 'User ID'
		dataType: int64
		formatString: 0
		lineageTag: 3ed8d59c-3626-41be-b5dd-1d6901737ce7
		summarizeBy: count
		sourceColumn: User ID

		annotation SummarizationSetBy = Automatic

	column Nom
		dataType: string
		lineageTag: 6a05df3e-9f3e-42ca-a107-fbd0ee843f84
		summarizeBy: none
		sourceColumn: Nom

		annotation SummarizationSetBy = Automatic

	column Prénom
		dataType: string
		lineageTag: 28c89afc-58bf-4fe9-9aab-c14f187c4549
		summarizeBy: none
		sourceColumn: Prénom

		annotation SummarizationSetBy = Automatic

	column Sexe
		dataType: string
		lineageTag: 1b2153ec-4ddc-4be5-843b-3ff14231daae
		summarizeBy: none
		sourceColumn: Sexe

		annotation SummarizationSetBy = Automatic

	column 'Date de naissance'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 645fe579-a3e2-4a60-b31c-d951c2d112c3
		summarizeBy: none
		sourceColumn: Date de naissance

		variation Variation
			isDefault
			relationship: 56f495ec-b69a-4fdd-b5df-d5f6850b5c00
			defaultHierarchy: LocalDateTable_c942538b-a49e-41a9-b2ec-6b2c1704c03d.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 95fac3c8-ca5d-4fb2-820c-6741dc91b490
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Date d''embauche'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3086a7da-b350-47d6-8a93-a23923424e86
		summarizeBy: none
		sourceColumn: Date d'embauche

		variation Variation
			isDefault
			relationship: 35970814-a0fd-444c-9c20-e23ec9f244b4
			defaultHierarchy: LocalDateTable_22e48b6b-2c02-4ab5-ab3e-3bad7b2b2947.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Direction
		dataType: string
		lineageTag: f1dc746e-0347-4919-bfef-2645797a85a8
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column Département
		dataType: string
		lineageTag: a3b2a706-1210-470d-a8cd-c5f55787392f
		summarizeBy: none
		sourceColumn: Département

		annotation SummarizationSetBy = Automatic

	column Service
		dataType: string
		lineageTag: d9069985-e7d0-4aab-be6f-73d9ff0bc58e
		summarizeBy: none
		sourceColumn: Service

		annotation SummarizationSetBy = Automatic

	column 'Poste harmonisé'
		dataType: string
		lineageTag: 2226fecc-96b3-421a-892a-db051b1bc60b
		summarizeBy: none
		sourceColumn: Poste harmonisé

		annotation SummarizationSetBy = Automatic

	column Fonction
		dataType: string
		lineageTag: fc44ebc1-a9ad-40f8-9683-b3157aa4ddd5
		summarizeBy: none
		sourceColumn: Fonction

		annotation SummarizationSetBy = Automatic

	column 'Date d''entrée'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e6826290-510b-48ab-b66a-071c3def82f9
		summarizeBy: none
		sourceColumn: Date d'entrée

		variation Variation
			isDefault
			relationship: 6fedab41-cb96-455f-a493-28604413bc8d
			defaultHierarchy: LocalDateTable_3bbe165a-7104-4fc1-b68c-2bb7a192ab93.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CODE Analytique'
		dataType: string
		lineageTag: 78ff79c6-433c-4f88-af67-104472825523
		summarizeBy: none
		sourceColumn: CODE Analytique

		annotation SummarizationSetBy = Automatic

	column 'Affectation Analytique '
		dataType: string
		lineageTag: 0b5c5659-f6ed-421c-bf51-e30ab3b630f8
		summarizeBy: none
		sourceColumn: "Affectation Analytique "

		annotation SummarizationSetBy = Automatic

	column 'Catégorie conventionnelle'
		dataType: string
		lineageTag: d3b493e7-a032-42ac-b276-25cdd8d43675
		summarizeBy: none
		sourceColumn: Catégorie conventionnelle

		annotation SummarizationSetBy = Automatic

	column 'Type de contrat'
		dataType: string
		lineageTag: 484229e7-c4e4-4d64-bcf6-de3638c37f25
		summarizeBy: none
		sourceColumn: Type de contrat

		annotation SummarizationSetBy = Automatic

	column 'Si CDD ou stagiaire, merci de préciser la date de fin de contrat'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3803a95a-f226-493a-bce5-5fb8abde69a4
		summarizeBy: none
		sourceColumn: Si CDD ou stagiaire, merci de préciser la date de fin de contrat

		variation Variation
			isDefault
			relationship: f16fa138-1963-4cec-8f80-2edeafa504d2
			defaultHierarchy: LocalDateTable_694eff86-5734-431a-b0f3-0e2f98e9e1ab.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Statut Local ou Expatrié?'
		dataType: string
		lineageTag: c04114be-561d-4993-97e8-697f1746c5c8
		summarizeBy: none
		sourceColumn: Statut Local ou Expatrié?

		annotation SummarizationSetBy = Automatic

	column Nationalité
		dataType: string
		lineageTag: 6783f5e1-ab69-4cf6-85a9-f2383a4598a2
		summarizeBy: none
		sourceColumn: Nationalité

		annotation SummarizationSetBy = Automatic

	column Ancienneté2
		dataType: int64
		formatString: 0
		lineageTag: 99b4de72-9cdf-4a35-8d11-eda4906d8497
		summarizeBy: sum
		sourceColumn: Ancienneté2

		annotation SummarizationSetBy = Automatic

	column 'Tranche d''age'
		dataType: string
		lineageTag: 898460c9-f12e-48f6-a917-c069d2aaf059
		summarizeBy: none
		sourceColumn: Tranche d'age

		annotation SummarizationSetBy = Automatic

	column 'Tranche d''ancienneté'
		dataType: string
		lineageTag: aeba1c22-313b-4273-9e29-c74accff014a
		summarizeBy: none
		sourceColumn: Tranche d'ancienneté

		annotation SummarizationSetBy = Automatic

	partition Tableau24 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("P:\PRESENTATION DATA RH\DONNEES RH Decembre 2025 MALI V2.xlsx"), null, true),
				    Tableau24_Table = Source{[Item="Tableau24",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(Tableau24_Table,{{"Type d'entrée dans la société", type text}, {"Motif de recrutement", type text}, {"Société", type text}, {"Matricule", type any}, {"User ID", Int64.Type}, {"Nom", type text}, {"Prénom", type text}, {"Sexe", type text}, {"Date de naissance", type date}, {"Age", Int64.Type}, {"Date d'embauche", type date}, {"Direction", type text}, {"Département", type text}, {"Service", type text}, {"Poste harmonisé", type text}, {"Fonction", type text}, {"Date d'entrée", type date}, {"CODE Analytique", type text}, {"Affectation Analytique ", type text}, {"Catégorie conventionnelle", type text}, {"Type de contrat", type text}, {"Si CDD ou stagiaire, merci de préciser la date de fin de contrat", type date}, {"Statut Local ou Expatrié?", type text}, {"Nationalité", type text}, {"Ancienneté2", Int64.Type}, {"Tranche d'age", type text}, {"Tranche d'ancienneté", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

